Repository NurkaAmre/Catalog-of-my-things, pull requests merged in 2023-01, with the labels that each got.

#19 Create game and author class
  Gemfile.lock
  f_classes/things/f_associations/author.rb
  f_classes/things/f_associations/genre.rb
  f_classes/things/f_associations/label.rb
  f_classes/things/game.rb
Labels: Create classes

#30 Rspec
  f_spec/genre_spec.rb
  f_spec/music_spec.rb
Labels: Unit test

#32 Final code ready for deployment
  .github/workflows/linters.yml
  .github/workflows/tests.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  LICENSE
  README.md
  app.rb
  f_classes/item.rb
  f_classes/things/book.rb
  f_classes/things/f_associations/author.rb
  f_classes/things/f_associations/genre.rb
  f_classes/things/f_associations/label.rb
  f_classes/things/game.rb
  f_classes/things/music_album.rb
  f_data_json/author.json
  f_data_json/books.json
  f_data_json/game.json
  f_data_json/genre.json
  f_data_json/labels.json
  f_data_json/music_album.json
  f_data_json/read_data.rb
  f_data_json/save_data.rb
  f_spec/author_spec.rb
  f_spec/book_spec.rb
  f_spec/game_spec.rb
  f_spec/genre_spec.rb
  f_spec/item_spec.rb
  f_spec/label_spec.rb
  f_spec/music_spec.rb
  interface_modules/display_options.rb
  interface_modules/process_option/add_book.rb
  interface_modules/process_option/add_game.rb
  interface_modules/process_option/add_music_album.rb
  interface_modules/process_option/associations/list_authors.rb
  interface_modules/process_option/associations/list_genres.rb
  interface_modules/process_option/associations/list_labels.rb
  interface_modules/process_option/list_books.rb
  interface_modules/process_option/list_games.rb
  interface_modules/process_option/list_music_albums.rb
  main.rb
  schema.sql
  src/hello.rb
Labels: Pull Request
